# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Caster/protos/input_reader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Caster.protos.data_preprocess_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Caster/protos/input_reader.proto',
  package='Caster.protos',
  serialized_pb=_b('\n Caster/protos/input_reader.proto\x12\rCaster.protos\x1a#Caster/protos/data_preprocess.proto\"\xae\x01\n\x0bInputReader\x12\x1a\n\x0c\x64\x61taset_name\x18\x01 \x01(\t:\x04ic15\x12\x19\n\x0bis_training\x18\x02 \x01(\x08:\x04true\x12\x38\n\x10tfrecord_decoder\x18\x03 \x01(\x0b\x32\x1e.Caster.protos.TfrecordDecoder\x12.\n\x0binput_batch\x18\x04 \x01(\x0b\x32\x19.Caster.protos.InputBatch\"\x8f\x01\n\x0fTfrecordDecoder\x12\x16\n\x0bnum_samples\x18\x01 \x01(\x05:\x01\x30\x12\x16\n\x0bnum_classes\x18\x02 \x01(\x05:\x01\x30\x12\x16\n\x0bnum_readers\x18\x03 \x01(\x05:\x01\x31\x12\x1c\n\x0equeue_capacity\x18\x04 \x01(\x05:\x04\x31\x30\x32\x34\x12\x16\n\tqueue_min\x18\x05 \x01(\x05:\x03\x35\x31\x32\"\x90\x01\n\nInputBatch\x12;\n\x11preprocess_option\x18\x01 \x03(\x0b\x32 .Caster.protos.PreprocessingStep\x12\x16\n\nbatch_size\x18\x02 \x01(\x05:\x02\x33\x32\x12\x16\n\x0bnum_threads\x18\x03 \x01(\x05:\x01\x34\x12\x15\n\x08\x63\x61pacity\x18\x04 \x01(\x05:\x03\x31\x32\x38')
  ,
  dependencies=[Caster.protos.data_preprocess_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INPUTREADER = _descriptor.Descriptor(
  name='InputReader',
  full_name='Caster.protos.InputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_name', full_name='Caster.protos.InputReader.dataset_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("ic15").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_training', full_name='Caster.protos.InputReader.is_training', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tfrecord_decoder', full_name='Caster.protos.InputReader.tfrecord_decoder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_batch', full_name='Caster.protos.InputReader.input_batch', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=263,
)


_TFRECORDDECODER = _descriptor.Descriptor(
  name='TfrecordDecoder',
  full_name='Caster.protos.TfrecordDecoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_samples', full_name='Caster.protos.TfrecordDecoder.num_samples', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='Caster.protos.TfrecordDecoder.num_classes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_readers', full_name='Caster.protos.TfrecordDecoder.num_readers', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queue_capacity', full_name='Caster.protos.TfrecordDecoder.queue_capacity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1024,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queue_min', full_name='Caster.protos.TfrecordDecoder.queue_min', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=512,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=409,
)


_INPUTBATCH = _descriptor.Descriptor(
  name='InputBatch',
  full_name='Caster.protos.InputBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preprocess_option', full_name='Caster.protos.InputBatch.preprocess_option', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='Caster.protos.InputBatch.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=32,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_threads', full_name='Caster.protos.InputBatch.num_threads', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='Caster.protos.InputBatch.capacity', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=556,
)

_INPUTREADER.fields_by_name['tfrecord_decoder'].message_type = _TFRECORDDECODER
_INPUTREADER.fields_by_name['input_batch'].message_type = _INPUTBATCH
_INPUTBATCH.fields_by_name['preprocess_option'].message_type = Caster.protos.data_preprocess_pb2._PREPROCESSINGSTEP
DESCRIPTOR.message_types_by_name['InputReader'] = _INPUTREADER
DESCRIPTOR.message_types_by_name['TfrecordDecoder'] = _TFRECORDDECODER
DESCRIPTOR.message_types_by_name['InputBatch'] = _INPUTBATCH

InputReader = _reflection.GeneratedProtocolMessageType('InputReader', (_message.Message,), dict(
  DESCRIPTOR = _INPUTREADER,
  __module__ = 'Caster.protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:Caster.protos.InputReader)
  ))
_sym_db.RegisterMessage(InputReader)

TfrecordDecoder = _reflection.GeneratedProtocolMessageType('TfrecordDecoder', (_message.Message,), dict(
  DESCRIPTOR = _TFRECORDDECODER,
  __module__ = 'Caster.protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:Caster.protos.TfrecordDecoder)
  ))
_sym_db.RegisterMessage(TfrecordDecoder)

InputBatch = _reflection.GeneratedProtocolMessageType('InputBatch', (_message.Message,), dict(
  DESCRIPTOR = _INPUTBATCH,
  __module__ = 'Caster.protos.input_reader_pb2'
  # @@protoc_insertion_point(class_scope:Caster.protos.InputBatch)
  ))
_sym_db.RegisterMessage(InputBatch)


# @@protoc_insertion_point(module_scope)
