# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Caster/protos/train.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Caster.protos.optimizer_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Caster/protos/train.proto',
  package='Caster.protos',
  serialized_pb=_b('\n\x19\x43\x61ster/protos/train.proto\x12\rCaster.protos\x1a\x1d\x43\x61ster/protos/optimizer.proto\"\xc8\x02\n\x0bTrainConfig\x12+\n\toptimizer\x18\x01 \x01(\x0b\x32\x18.Caster.protos.Optimizer\x12\x1c\n\rsync_replicas\x18\x02 \x01(\x08:\x05\x66\x61lse\x12#\n\x14\x66ine_tune_pretrained\x18\x03 \x01(\x08:\x05\x66\x61lse\x12+\n\x1dkeep_checkpoint_every_n_hours\x18\x04 \x01(\r:\x04\x31\x30\x30\x30\x12\x14\n\tnum_steps\x18\x05 \x01(\r:\x01\x30\x12!\n\x14save_checkpoint_secs\x18\x06 \x01(\x05:\x03\x36\x30\x30\x12!\n\x14save_summaries_steps\x18\x07 \x01(\x05:\x03\x31\x30\x30\x12 \n\x15replicas_to_aggregate\x18\x08 \x01(\x05:\x01\x31\x12\x1e\n\x12total_num_replicas\x18\t \x01(\x05:\x02\x31\x35')
  ,
  dependencies=[Caster.protos.optimizer_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='Caster.protos.TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='optimizer', full_name='Caster.protos.TrainConfig.optimizer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_replicas', full_name='Caster.protos.TrainConfig.sync_replicas', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fine_tune_pretrained', full_name='Caster.protos.TrainConfig.fine_tune_pretrained', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_checkpoint_every_n_hours', full_name='Caster.protos.TrainConfig.keep_checkpoint_every_n_hours', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_steps', full_name='Caster.protos.TrainConfig.num_steps', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_checkpoint_secs', full_name='Caster.protos.TrainConfig.save_checkpoint_secs', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=600,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_summaries_steps', full_name='Caster.protos.TrainConfig.save_summaries_steps', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replicas_to_aggregate', full_name='Caster.protos.TrainConfig.replicas_to_aggregate', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_num_replicas', full_name='Caster.protos.TrainConfig.total_num_replicas', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=404,
)

_TRAINCONFIG.fields_by_name['optimizer'].message_type = Caster.protos.optimizer_pb2._OPTIMIZER
DESCRIPTOR.message_types_by_name['TrainConfig'] = _TRAINCONFIG

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINCONFIG,
  __module__ = 'Caster.protos.train_pb2'
  # @@protoc_insertion_point(class_scope:Caster.protos.TrainConfig)
  ))
_sym_db.RegisterMessage(TrainConfig)


# @@protoc_insertion_point(module_scope)
